@Api_HostAddress = http://localhost:5174

### Get all password entries (previews)
GET {{Api_HostAddress}}/api/password
Accept: application/json

### Get specific password entry (detail)
GET {{Api_HostAddress}}/api/password/3
Accept: application/json

### Create a new password entry
POST {{Api_HostAddress}}/api/password
Content-Type: application/json

{
    "name": "test url",
    "username": "hugo@example.com",
    "password": "MySecretPassword1234"
}