@Api_HostAddress = http://localhost:5174

### Get all password entries (previews)
GET {{Api_HostAddress}}/api/password
Accept: application/json

### Create a new password entry
POST {{Api_HostAddress}}/api/password/Create
Content-Type: application/json

{
    "name": "My Email",
    "username": "hugo@example.com",
    "encryptedPassword": "MySecretPassword123",
    "salt": "123456768900",
    "iv": "2839892832"
}